[package]
name = "tenjin_sdn"
description = "The software defined network and Openflow protocol"
version = "0.3.2"
authors = ["Nawasan <nawasan.dev@gmail.com>"]
license = "MIT"
edition = "2021"
readme = "README.md"
repository = "https://github.com/Arikato111/Tenjin"
categories = ["command-line-utilities"]
keywords = ["sdn", "cli", "openflow"]

include = ["src/*"]

[lib]
name = "tenjin"
path = "src/lib.rs"

[[bin]]
name = "tenjin"
path = "src/main.rs"

[dependencies]
byteorder = "1.0.0"
clap = { version = "4.5.13", features = ["derive"] }

[profile.release]
strip = true
