name: Build and Publish Rust Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: . # Path to your Dockerfile
          file: ./Dockerfile # Path to your Dockerfile. Adjust if needed.
          push: true
          tags: |
            ghcr.io/arikato111/tenjin:latest
            ghcr.io/arikato111/tenjin:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
